services:
  postgres:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root1
      POSTGRES_PASSWORD: root
      POSTGRES_DB: GameStoreDb
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root1 -d GameStoreDb"]
      interval: 5s
      timeout: 5s
      retries: 10

  webapp:
    build: ./back
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=GameStoreDb;Username=root1;Password=root
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./front
   
    depends_on:
      - webapp

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
      - frontend

volumes:
  postgres_data: